### ISSUE TITLE
consigne pas clair

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#101]
la consigne explique comment faire la fonction ET comment l'utiliser pour trouver la colonne du baggle, alors que seule la fonction est demandée

**Comment by mquinson** [comment]
I **think** that this report is about  https://plm.telecomnancy.univ-lorraine.fr/#/ui/lessons/welcome/variables.Variables but I'm not sure. And I disagree with the report, this point is quite clear to me.

Other advices?

**Comment by MatthieuNICOLAS** [comment]
I would rather say that this issue is about [MethodsReturning](https://plm.telecomnancy.univ-lorraine.fr/#/ui/lessons/welcome/methods.returning.MethodsReturning). Indeed, many students didn't understand that they did not have to write the code to move between columns and call ```haveBaggle()```.
