### ISSUE TITLE
If the direction is wrong, the error message is about a mismatching color (it says "red != red") 

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#108]
Si la buggle n'est pas dans la bonne direction à la fin de l'exercice, il semblerait que le message d'erreur indique que la brosse du buggle n'est pas de la bonne couleur (rouge attendu, rouge effectif)

**Comment by mquinson** [comment]
Fixed in https://github.com/BuggleInc/PLM/commit/12e0d035a1ab9e9ee00e63ac7cc4ee014dab9c5f
