### ISSUE TITLE
La Souris Folle

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#116]
Voici l'erreur affichée : The world 'Swiss cheese' differs: Il y a quelque chose qui cloche avec la buggle «Thesee»: Sa couleur est java.awt.Color[r=0,g=0,b=0] ; attendue : java.awt.Color[r=0,g=0,b=0]. La couleur de son pinceau est java.awt.Color[r=192,g=192,b=192] ; attendue : java.awt.Color[r=192,g=192,b=192] Elle ne porte pas de biscuit. 

Alors que l'on voit bien que la buggle prend le biscuit à la fin !
Surtout que ce code fonctionne pour un des mondes.

Et voici le code:
override def run() {
  while(!estSurBiscuit){
    var entier = random3()
    if (entier ==0){
      if(!estFaceMur){
        avance
      }
    }
    if(entier==1){
      droite()
    }
    else{
      gauche()
    }
  }
  prendBiscuit()
    
}

**Comment by MatthieuNICOLAS** [comment]
The issue here is the direction of the Buggle at the end of the execution. Since the user is not using ```if/else if/else``` but ```if/if/else```, the buggle turns left before picking up the baggle.
The error message is misleading and should be fixed.

**Comment by mquinson** [comment]
This is thus a dupplicate of #108.
