### ISSUE TITLE
Le problème du drapeau hollandais

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#127]
Le drapeau indiqué dans l'objectif est inversé par rapport au drapeau réel des pays bas.
https://fr.wikipedia.org/wiki/Pays-Bas#/media/File:Flag_of_the_Netherlands.svg

**Comment by mquinson** [comment]
I blame the UI for displaying them in the wrong order :) In fact, the old 2.6 Java version displays them in the right order, I just checked.
