### ISSUE TITLE
Error in the Rainbow Baseball help text

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#129]
In /ui/lessons/sort.baseball/#drawingArea.

"So base 1 is of color 1. In the graphical interface, the base 0 is the dark blue one while the base 1 is the fuscia one."

The base 1 is the brown one and not the fuscia one which is 2.

--

Lesson: sort.baseball
Exercise: sort.baseball.NaiveBaseball
Programming Language: Scala
Lang: en
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM4915a8fad87dac567d8dc71ce7add86c5b40d787

**Comment by mquinson** [comment]
Well, the UI should use the right colors if possible. That'd be easier than fixing each and every descriptions and translations.
