### ISSUE TITLE
Indication manquante

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#131]
Il manque les indications concernant les rayons des cercles.

--

Lesson: turtleart
Exercise: turtleart.circletwo.CircleTwo
Programming Language: Scala
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM9444992219e14979ce5a4f45ce34f7eb934a1fa2

**Comment by mquinson** [comment]
The circle radius is useless to solve the exercise, thus closing.
