### ISSUE TITLE
CircleYing - manque indications

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#135]
Salut ! Il manque les rayons des cercles sur l'exercice CircleYing.

--

Lesson: turtleart
Exercise: turtleart.circleying.CircleYing
Programming Language: Scala
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM9444992219e14979ce5a4f45ce34f7eb934a1fa2

**Comment by mquinson** [comment]
radius are of no use for this exercise.
