### ISSUE TITLE
CircleTen - manque indications

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#136]
Salut ! Il manque le rayon des cercles (10*i for (i <- 1 to 10)), il faut chercher à la main et à l’œil du coup.

--

Lesson: turtleart
Exercise: turtleart.circleten.CircleTen
Programming Language: Scala
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM9444992219e14979ce5a4f45ce34f7eb934a1fa2

**Comment by mquinson** [comment]
Oui, c'est l'idée de chercher à l'oeil sur cet exo :)
