### ISSUE TITLE
Polygone 360

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#137]
Erreur d'arrondie entrainant la non-validation de l'exercice

--

Lesson: turtleart
Exercise: turtleart.polygon360.Polygon360
Programming Language: Scala
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLMaa6c3cb4ccdeeb8a53da7c96e37081d092c9fb72

**Comment by mquinson** [comment]
There is nothing we can do without the faulty code. Thus closing.
