### ISSUE TITLE
incomplete translation

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#141]
in the Portuguese translation, action button ain't translated (sign in /out) which is done in French
also test button ain't translated in any languages

--

Lesson: sort.baseball
Exercise: sort.baseball.NaiveBaseball
Programming Language: Scala
Lang: pt
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM3c61b5275d4062ac8618571fcd0beb335404c2aa

**Comment by mquinson** [comment]
Incomplete translations are not worth reporting as a bug...
