### ISSUE TITLE
instruction etrange

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#142]
dans NaiveBaseball, on nous annouce que la base 0 est la base bleu, et que la 1 est la base fushia, cela est absolument incohérent avec le dessin qui montre ces deux bases opposées
cette erreur est présente en français comme en anglais

--

Lesson: sort.baseball
Exercise: sort.baseball.NaiveBaseball
Programming Language: Scala
Lang: en
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM3c61b5275d4062ac8618571fcd0beb335404c2aa

**Comment by mquinson** [comment]
Duplicate of  #129, thus closing.
