### ISSUE TITLE
translation incomplete

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#143]
the help of the portuguese translation is still in english !!

--

Lesson: sort.baseball
Exercise: sort.baseball.NaiveBaseball
Programming Language: Scala
Lang: pt
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM3c61b5275d4062ac8618571fcd0beb335404c2aa

**Comment by mquinson** [comment]
please help us by translating it :)

I'm closing the bug because we already have the list of missing translations elsewhere and I'd like to have this dashboard clear and readable.
