### ISSUE TITLE
traduction fausse

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#145]
le texte accompagnant le premier tri de crêpes est incorrecte : ce n'est pas la pile qui est de rang 0, mais bien la crêpe du dessus comme dans la description anglaise (deuxième paragraphe en partant du bas)

--

Lesson: sort.pancake
Exercise: sort.pancake.BasicPancake
Programming Language: Scala
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM3c61b5275d4062ac8618571fcd0beb335404c2aa

**Comment by mquinson** [comment]
Here is the translation of the second last paragraph. I don't see no problem. Anyone, am I blind?

```
msgid ""
"Your work is to help this poor guy sorting his stack by flipping the "
"pancakes. Each pancake is defined by its radius and rank within the stack, "
"with the top-most pancake is at rank 0, and the one below at rank 1."
msgstr ""
"Vous devez aider ce pauvre homme à trier sa pile en retournant des crêpes. "
"Chaque crêpe est définie par son rayon et son rang dans la pile. La pile la "
"plus haute est de rang 0, et celle placée au dessous d'elle est de rang 1."
```

**Comment by mquinson** [comment]
Really, this bug seem buggy to me.
