### ISSUE TITLE
Proposer des corrections aux défis ?

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#146]
Est-il possible d'avoir une proposition de correction à chaque fois qu'un défis est validée pour avoir un autre point de vue?

--

Lesson: maze
Exercise: maze.pledge.PledgeMaze
Programming Language: Scala
Lang: en
PLM version: 2.6-pre (20150202)
webPLM version: 2.1.0
Public user ID: PLMbbd55f9b3ddab0e62067274b83b70f9bf4040441

**Comment by mquinson** [comment]
La philosophie de la PLM est de dire qu'il n'y a pas une seule façon de résoudre un exercice, et que le résultat prime sur la manière. C'est pour  cela que nous ne proposons pas de correction. Je ne pense pas que ça change dans un avenir proche. Désolé.
