### ISSUE TITLE
Pancake Sorting: flip(n) should take the pancake rank

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#149]
La fonction "flip" devrait prendre en argument le rang d'un pancake, plutot que le nombre de pancake à retourner, pour respecter la cohérence avec les précédentes fonctions.

--

Lesson: sort.pancake
Exercise: sort.pancake.BasicPancake
Programming Language: Scala
Lang: en
PLM version: 2.6-pre (20150202)
webPLM version: 2.0.3
Public user ID: PLM26ea89916752d348768ef5f6397fcfdf7212d69a

**Comment by mquinson** [comment]
C'est le premier exercice de la série. Je ne vois pas avec quelles fonctions précédentes on cherche la cohérence. Faute d'éléments supplémentaires, je serais contraint de fermer le bug.

**Comment by mquinson** [comment]
A la réflexion, la proposition est impossible à implémenter car la pelle à crêpe se place entre deux crêpes, pas à une crêpe donnée. Je pense que parler de rang serait piégeux et je préfère ne pas le faire.
