### ISSUE TITLE
Illustrations manquantes tri rapide des crêpes

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#153]
Bonjour ! Les images illustratives pour le tri rapide des crêpes ne s'affichent pas. :(

--

Lesson: sort.pancake
Exercise: sort.pancake.GatesPancake
Programming Language: Scala
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.1.0
Public user ID: PLM9444992219e14979ce5a4f45ce34f7eb934a1fa2

**Comment by mquinson** [comment]
Hello, this is fixed in the git version already.
