### ISSUE TITLE
Feature "submit a bug" not working

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/webPLM#28]
This feature is utterly important to capture the feedback of the users, and we really need it before getting in production.

In addition, now that we have the web interface (and if possible), we should try to use the github identity of the user and switch to the John Doe identity only if needed. But that may be another issue.

**Comment by MatthieuNICOLAS** [comment]
The main feature has been implemented with ebe0c8dea9bdd1b92c9ba0180f48f69750512063.
The other issue, using the user's github identity when creating an issue, is now referenced here: https://github.com/BuggleInc/webPLM/issues/40.

Thus closing this one.
