### ISSUE TITLE
sysouts of the students should appear in the console in the web page

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/webPLM#32]
We spoke about it. Filling the bug so that we don't forget.

The current content of the console (the error message from the world comparison) should then be moved elsewhere, I guess. Maybe we can make them visible in an overlay that appears when you hit a little magnifying glass or something.

**Comment by MatthieuNICOLAS** [comment]
Fix with 52f6d94c72a4fa9e7beee0a350dad0edd056d91b  thus closing it.
