### ISSUE TITLE
Name reported as "null null" if no firstname/lastname given

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/webPLM#44]
Here is a screenshot. I guess that we are missing a little test somewhere.

![bug-plm-null-null](https://cloud.githubusercontent.com/assets/624847/9184746/635ce00e-3fb7-11e5-9b67-ba6620b3d364.png)

**Comment by mquinson** [comment]
In addition, if I only give my first name, my identifyier becomes "Martin undefined". Not nice either :)

**Comment by mquinson** [comment]
Addition: I was connected through the PLM authentication service.

**Comment by mquinson** [comment]
I just reconnected with github, and my identifier is now "Martin null". It may well be the case that my previous comment was wrong: I was connected through github, not the PLM authentication service (sorry).

**Comment by oster** [comment]
This seems to be fixed in the current deployed version.

We could just improve the field checking mechanisms (the order in which the checks are performed, the clue for the minimum password size, the message for approval, etc.à
