### ISSUE TITLE
Le rouge sur rouge c'est pas la joie

### ISSUE THREAD

**Issue by Minious** [BuggleInc/webPLM#50]
Le premier exo de la catégorie Snake World de Welcome m'a posé un petit soucis avec l'erreur "something is wrong with Buggle" ou un truc dans ce genre là. Il s'avère que le buggle était tout simplement mal orienté à la fin du programme (au Nord tandis que la solution devait être Est). Ce problème était cependant difficilement décelable étant donné que le buggle recouvre l'ensemble de quadrillage de rouge et qu'il est lui-même ... ROUGE eh oui ! Un petit changement de couleur pourrait s'avérer opportun.
Salutations.

**Comment by mquinson** [comment]
This issue was moved to BuggleInc/PLM#466

**Comment by mquinson** [comment]
I moved this issue to the PLM repo that hosts the lessons, using https://github-issue-mover.appspot.com/
