### ISSUE TITLE
Problème Exercice du Ticket Bleu

### ISSUE THREAD

**Issue by Quazar59** [BuggleInc/webPLM#51]
Le code suivant semble correct, pourtant il bloque avec la combinaison (9,2,0):

def blueTicket(a:Int, b:Int, c:Int):Int = {var ab = a+b;
                                           var bc = b+c;
                                           var ac = a+c;
                                           var  a0:Int = ab - 10;
                                           (ab,bc,ac) match {
                                             case (10,_,_) => return 10
                                             case (_,10,_) => return 10
                                             case (_,_,10) => return 10
                                             case (_,a0,_) => return 5
                                             case (_,_,a0) => return 5
                                             case(_,_,_) => return 0}
                                           }

**Comment by MatthieuNICOLAS** [comment]
Après vérification, il semblerait qu'une fonctionnalité de Scala soit la raison de ce bug:

Pour utiliser une valeur dans un *match*, il faut que celle-ci soit contenue dans une **constante** ET que le **nom de cette constante commence par une majuscule**.
Pour corriger ton code, il suffit donc de renommer *a0* en *A0* et de la déclarer en tant que constante avec *val* plutôt que *var*.

Voici [un thread](http://stackoverflow.com/questions/4479474/scala-pattern-matching-with-lowercase-variable-name) discutant de cette particuliarité de Scala.

Bonne journée!
