### ISSUE TITLE
Buttons display

### ISSUE THREAD

**Issue by Kaendan** [BuggleInc/webPLM#7]
Because the French words for the "Revert" and "Switch" are longer than the English version, the buttons' display changes. When the application is in french on a 13" screen, the display seems strange.

**Comment by mquinson** [comment]
@MatthieuNICOLAS it seems to me that this bug is now fixed. Am I right?

**Comment by MatthieuNICOLAS** [comment]
Yep, the UI has been revamped since then, solving this issue incidentally. So closing it.
