### ISSUE TITLE
Authentication (sign up) fails

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/webPLM#70]
When trying again to sign up from home (where I'm not filtered), this still fails in a new and unexpected way. 

![servererror](https://cloud.githubusercontent.com/assets/624847/11102389/808a40d8-88bc-11e5-9904-b08a9fb2da65.png)

**Comment by mquinson** [comment]
Cannot reproduce anymore.

**Comment by MatthieuNICOLAS** [comment]
It has been solved with the release of the new version of [BuggleInc/PLM-accounts](https://github.com/BuggleInc/PLM-accounts). Thus closing it.
